### ISSUE TITLE
RailsSchemaUpToDate has spurious errors

### ISSUE THREAD

**Issue by wli** [brigade/overcommit#252] opened 2015-07-14 01:03 UTC
Here's are two scenarios in which a spurious error is thrown. Both of these problems arise in a multi-developer PR workflow where multiple people are modifying the schema at the same time.

### Base Scenario ###
Let's say `db/schema.rb` is at version 1000

First pull request:
 - add `db/migrate/2345.rb`
 - `db/schema.rb` is updated to version 2345

Second pull request:
 - add `db/migrate/1234.rb`
 - db/schema.rb is updated to version 1234

### Failure 1 ###
If the first pull request gets merged in, and the second author merges/rebases to pick up the changes, their PR now looks like:
 - add `db/migrate/1234.rb`
 - `db/schema.rb` is at version 2345 (it doesn't change because you keep the higher number: http://edgeguides.rubyonrails.org/active_record_migrations.html#schema-dumps-and-source-control)

For normal migrations, this is just fine and `overcommit` won't complain since there will be table/column changes in `schema.rb`. However, if the migration doesn't change any tables or columns (for example, a data migration that normalizes phone numbers), the error that gets triggered is: "It looks like you're adding a migration, but did not update the schema file".

I'm not sure how best to solve this other than setting it to just `:warn` instead of `:fail`. 
https://github.com/brigade/overcommit/blob/6c259b7ec504055ffef64cdd50b24a37b6e552f5/lib/overcommit/hook/pre_commit/rails_schema_up_to_date.rb#L6

### Failure 2 ###
The following error can get thrown if PR2 gets merged in first.

````
return :fail, "The latest migration version you're committing is " \
                       "#{latest_version}, but your schema file " \
                       "#{schema_files.join(' or ')} is on a different version."
````

`latest_version` is now 1234 (since it scans for `applicable_files` and doesn't find 2345), but `db/schema.rb` only stores the latest number 2345 (`db/structure.sql` stores all versions, so it doesn't have this problem).

This can be fixed by looking at all possible migration files to find `latest_version` instead of just from the `applicable_files` set.

**Comment by sds** [comment] 2015-07-14 03:40
Thanks for the report, @wli.

@jfelchner, any thoughts on this?

**Comment by sds** [comment] 2016-01-26 20:12
We've been using this hook at @brigade and haven't experienced the issues reported here, but I'm sure it's dependent on the development process we use (we use a cherry-pick model and rebase frequently on top of master). Perhaps we've just gotten lucky.

Always happy to accept a pull request fixing this, but I'm closing due to lack of movement.

**Closed by sds** 2016-01-26 20:12 UTC
Labels: bug

**Comment by jfelchner** [comment] 2016-01-26 20:13
@sds yeah I tried to track it down and couldn't reproduce.
