### ISSUE TITLE
Brakeman integration broken

### ISSUE THREAD

**Issue by kalkin** [brigade/overcommit#283] opened 2015-10-03 14:48 UTC
- The brakeman integration runs only on the to be file to be commited. This suppresses errors and warnings. I.e try to run it with '-A' on some controller in a RoR app which has warnings. The warnings will not be shown.

- If you specify some flags like `-A` you need to make sure to add `--only-files` to the end of your flags.

**Comment by sds** [comment] 2015-10-03 18:55
Hey @kalkin,

> - The brakeman integration runs only on the to be file to be commited. This suppresses errors and warnings. I.e try to run it with '-A' on some controller in a RoR app which has warnings. The warnings will not be shown.

This is expected behavior, although it's understandable why this would be confusing given the purpose of Brakeman is typically to run against your entire repository. Overcommit pre-commit hooks aren't designed that way&mdash;they're intended to be run against files that have changed and are about to be committed.

The issue of how useful the Brakeman hook would be was raised in the original pull request (#50). Personally, I think it makes more sense as a separate check run via CI instead of as a pre-commit hook.

> - If you specify some flags like `-A` you need to make sure to add `--only-files` to the end of your flags.

This is also expected behavior. The list of default flags is defined in [`config/default.yml`](https://github.com/brigade/overcommit/blob/v0.28.0/config/default.yml#L139), so if you add flags you need to specify the original list in addition to the flags you are adding.

Hope that helps explain things.

**Closed by sds** 2015-10-03 18:55 UTC
Labels: question

**Comment by kalkin** [comment] 2015-10-03 20:34
@sds Thank you for your answer. You are right i should have read the #50 more carefully. Could you link it in the README besides the Brakeman listing? This would be probably helpful.
