### ISSUE TITLE
Error:undefined method `load_repo_config'

### ISSUE THREAD

**Issue by daniel-lanciana** [brigade/overcommit#563] opened 2018-02-28 17:43 UTC
1. Installed the gem
2. Installed in my project
3. Attempting to commit results in the following error:

`Error:undefined method load_repo_config for Overcommit::ConfigurationLoader:Class
Did you mean?  load_from_file
.git/hooks/pre-commit:52:in <main>
Report this bug at https://github.com/brigade/overcommit/issues`

Any ideas? Thanks.

**Comment by sds** [comment] 2018-03-08 06:31
Hey @daniel-lanciana,

`.git/hooks/pre-commit:52` doesn't make sense for a line number in this case, as that points to an [`else`](https://github.com/brigade/overcommit/blob/343633687b975b3899cb9a4ebadb34a0bb1f5272/template-dir/hooks/pre-commit#L52) statement in the latest version of Overcommit (0.43.0 at time of writing).

There's not enough information here to debug further, but I would say that Overcommit is not correctly installed, given the backtrace you've shared. I'm not sure how you got it to that state, so any additional information would be helpful here.

**Comment by sds** [comment] 2018-07-27 20:04
Closing due to lack of additional information. Feel free to open a new PR with reproducible steps!

**Closed by sds** 2018-07-27 20:04 UTC
Labels: need-more-info
