### ISSUE TITLE
Possibility to run hooks inside a virtualized container

### ISSUE THREAD

**Issue by waiting-for-dev** [brigade/overcommit#453] opened 2016-11-25 08:31 UTC
Hi!

I use to run my application specific development environment inside a docker container, while I use a common setup for my generic development tools (git, vim...).

Before digging into overcommit code base and maybe submitting a pull request, I wanted to ask you whether you think it would be possible/easy to configure it to execute all hooks within a docker container (for example, prefixing executables with `docker-compose exec app`).

I know I could also run git within the container along with overcommit and all the engines, but I don't like the idea of having to configure a cross-project tool (like git) for each single container.

My idea is to just install overcommit in my development machine, while all the other engines should go within the container. Then git and overcommit would run in my physical machine, and then overcommit would dispatch all executables to the container. Even I'm not sure if it would be possible to install and run overcommit itself in the container.

This need is more flagrant when you consider some engines like `rspec`, which usually requires all the application Gemfile to be installed (along with all needed OS libreries).

Thanks

**Comment by solars** [comment] 2016-12-07 18:33
I'm also wondering how I would use overcommit with docker images.. I'm commiting outside of the container, the problem is rubocop for example is not available there

**Comment by sds** [comment] 2016-12-14 05:56
Hey @waiting-for-dev,

I don't have a good answer for your question. A tool we use at @brigade ([Dock](https://github.com/brigade/dock)) allows you to modify the shebang line of a script to have it [automatically run in a Docker container](https://github.com/brigade/dock#automatically-execute-a-script-in-a-dock-container).

You could modify the git hooks that Overcommit installs in your repository's `.git/hooks` directory to have the appropriate shebang line.

Definitely open to suggestions you have on how to tackle this problem. Won't be able to get to this myself, but a pull request with tests would be most welcome!

**Comment by waiting-for-dev** [comment] 2016-12-14 08:09
Thanks for your answer @sds . I'll look into it and report here if I find a good solution :)

**Comment by k-rudy** [comment] 2017-12-09 23:49
@waiting-for-dev did you manage to have it working at the end?

**Comment by waiting-for-dev** [comment] 2017-12-10 08:05
Not really @k-rudy , what I've been doing is installing overcommit and its engines in the container and manually run `docker-compose exec app overcommit -r` before each push.

**Comment by sds** [comment] 2018-02-11 20:47
I don't think there's a one-size-fits-all solution to this problem. If you want to run the entire Overcommit run in a container, that might be useful but then you have the hassle of installing all the necessary software in that container (e.g. all the linters and tools run by your hooks)

On the other hand, you could use [ad hoc hooks](https://github.com/brigade/overcommit#adding-existing-git-hooks) to run hooks via `docker run` commands, but now you have to create a container for each of these hooks.

I don't think it makes sense for Overcommit to provide a built-in solution here, given the flexibility developers will likely want. Closing this for now. Thanks for sharing your thoughts/ideas!

**Closed by sds** 2018-02-11 20:47 UTC
Labels: enhancement
