### ISSUE TITLE
Rubocop .git/index: index file open failed: Not a directory

### ISSUE THREAD

**Issue by deanputney** [brigade/overcommit#383] opened 2016-06-06 19:43 UTC
When running a commit with overcommit on, Rubocop reports an unusual error:

```
$ git ci -m "Small change"
Running pre-commit hooks
Analyze with RuboCop........................................[RuboCop] FAILED
Errors:
fatal: .git/index: index file open failed: Not a directory
fatal: .git/index: index file open failed: Not a directory
fatal: Not a git repository: '.git'
```

The git index exists and git functions normally otherwise. Git is able to make a commit when skipping Rubocop. Rubocop behaves normally outside of overcommit. So far I haven't been able to find precedence on the `Not a directory` portion of this error.

Is there a way to determine which `.git/index` files overcommit is trying to access? The repository has a few submodules, which may be why the error is repeated more than once.

**Comment by sds** [comment] 2016-06-06 20:09
Hey @deanputney,

* What other hooks are you running? (your `.overcommit.yml` would be helpful) 
* Are there any hooks which are running `git` commands directly? (i.e. hooks that you wrote)
* Are you on JRuby or some non-MRI Ruby runtime?

**Comment by sds** [comment] 2016-06-06 20:11
Also, the message `Not a git repository: '.git'` is telling. Which directory are you running `git ci -m ...` from?

**Comment by deanputney** [comment] 2016-06-06 20:17
Hi @sds 

* RuboCop is the first hook to run, and it throws this error before other hooks are called. My `.overcommit.yml` file also includes EsLint and runs the default hooks. Here's the RuboCop portion:

```
PreCommit:
  RuboCop:
    enabled: true
    flags: ['--format=emacs', '--force-exclusion', '--display-cop-names', '--config', 'config/.rubocop.yml']
    exclude:
      - <exclude directories>
    problem_on_unmodified_line: ignore
```

`config` is a submodule.

* There are no hooks I wrote under PreCommit. Just RuboCop and EsLint.
* I'm running Ruby with RVM: `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]`
* I'm running my commit command from the root of my repository. The `.git` directory is visible in `ls -lah`. I've also cloned a fresh copy of the repository to be sure there's no unusual permissions issue or something similar.

**Comment by jawshooah** [comment] 2016-06-06 20:19
Could you try again with `OVERCOMMIT_DEBUG=1` and post the output?

**Comment by deanputney** [comment] 2016-06-06 20:27
```
$ OVERCOMMIT_DEBUG=1 git ci -m "Small change"
git rev-parse --git-dir
EXIT STATUS: 0
STDOUT: ".git\n"
STDERR: ""
git config --local --get overcommit.configuration.signature
EXIT STATUS: 0
STDOUT: "1156ce2f0f71ffeecde5ed255ab43f9a728118c5aad38d3f087de9dbe8a063f4\n"
STDERR: ""
git config --local --get overcommit.configuration.signature
EXIT STATUS: 0
STDOUT: "1156ce2f0f71ffeecde5ed255ab43f9a728118c5aad38d3f087de9dbe8a063f4\n"
STDERR: ""
git rev-parse HEAD
EXIT STATUS: 0
STDOUT: "e086f18a336fb5b0918acd667f90af62d07dc215\n"
STDERR: ""
git stash save --keep-index --quiet Overcommit: Stash of repo state before hook run at 2016-06-06 13:19:31 -0700
EXIT STATUS: 0
STDOUT: ""
STDERR: ""
Running pre-commit hooks
rubocop --format=emacs --force-exclusion --display-cop-names --config config_common/development/.rubocop.yml ... (1 splittable args)
git config --get user.email
grep -IHn ^<<<<<<<[ 	] ... (1 splittable args)
git config --get user.name
git rev-parse HEAD
EXIT STATUS: 0
STDOUT: "dean@domain.com\n"
STDERR: ""
EXIT STATUS: 0
STDOUT: "Dean Putney\n"
STDERR: ""
EXIT STATUS: 0
STDOUT: "e086f18a336f7f90af62d07db5b0918acd66c215\n"
STDERR: ""
EXIT STATUS: 1
STDOUT: ""
STDERR: ""
EXIT STATUS: 1
STDOUT: "/Users/deanputney/project1/app/models/file.rb:26:3: W: Lint/UselessAccessModifier: Useless `private` access modifier.\n"
STDERR: "fatal: .git/index: index file open failed: Not a directory\nfatal: .git/index: index file open failed: Not a directory\nfatal: Not a git repository: '.git'\n"
Analyze with RuboCop........................................[RuboCop] FAILED
Errors:
fatal: .git/index: index file open failed: Not a directory
fatal: .git/index: index file open failed: Not a directory
fatal: Not a git repository: '.git'


✗ One or more pre-commit hooks failed

git reset --hard
EXIT STATUS: 0
STDOUT: "HEAD is now at e086f18 Adding TODO comment\n"
STDERR: ""
git stash pop --index --quiet
EXIT STATUS: 0
STDOUT: ""
STDERR: ""
```

**Comment by sds** [comment] 2016-06-06 20:34
Thanks for the additional output, @deanputney.

Again, the error message suggests there's something funny going on here. `git` is saying that `.git` is not a directory, which is odd.

What happens if you run `OVERCOMMIT_DEBUG=1 ONLY=RuboCop git ci -m "Small change"`?

**Comment by deanputney** [comment] 2016-06-06 20:38
@sds Not a whole lot different... I get a couple extra skip messages, but precisely the same output surrounding the error.

Is there some way to see the full path to the `.git` it's trying to access? Maybe it's confused about its path somehow?

**Comment by sds** [comment] 2016-06-06 20:40
The hook should be running with the root of the repository as its working directory.

For sanity's sake, let's remove parallelism as a potential cause: what happens if you add `concurrency: 1` to the top of your `.overcommit.yml` (outlined here: https://github.com/brigade/overcommit#concurrency)

**Comment by deanputney** [comment] 2016-06-06 20:46
Same error, slightly different order (as expected, but not in a helpful way it seems):

```
$ OVERCOMMIT_DEBUG=1 ONLY=RuboCop git ci -m "Small change"
git rev-parse --git-dir
EXIT STATUS: 0
STDOUT: ".git\n"
STDERR: ""
git config --local --get overcommit.configuration.signature
EXIT STATUS: 0
STDOUT: "1156ce2f0f71ffeecde5ed255ab43f9a728118c5aad38d3f087de9dbe8a063f4\n"
STDERR: ""
git config --local --get overcommit.configuration.signature
EXIT STATUS: 0
STDOUT: "1156ce2f0f71ffeecde5ed255ab43f9a728118c5aad38d3f087de9dbe8a063f4\n"
STDERR: ""
git rev-parse HEAD
EXIT STATUS: 0
STDOUT: "e086f18a336fb5b0918acd667f90af62d07dc215\n"
STDERR: ""
git stash save --keep-index --quiet Overcommit: Stash of repo state before hook run at 2016-06-06 13:41:33 -0700
EXIT STATUS: 0
STDOUT: ""
STDERR: ""
Running pre-commit hooks
rubocop --format=emacs --force-exclusion --display-cop-names --config config/.rubocop.yml ... (1 splittable args)
EXIT STATUS: 1
STDOUT: "/Users/deanputney/project1/app/models/file.rb:26:3: W: Lint/UselessAccessModifier: Useless `private` access modifier.\n"
STDERR: "fatal: .git/index: index file open failed: Not a directory\nfatal: .git/index: index file open failed: Not a directory\nfatal: Not a git repository: '.git'\n"
Analyze with RuboCop........................................[RuboCop] FAILED
Errors:
fatal: .git/index: index file open failed: Not a directory
fatal: .git/index: index file open failed: Not a directory
fatal: Not a git repository: '.git'

Skipping MergeConflicts
Cannot skip AuthorEmail since it is required
git config --get user.email
EXIT STATUS: 0
STDOUT: "dean@domain.com\n"
STDERR: ""
Skipping BrokenSymlinks
Cannot skip AuthorName since it is required
git config --get user.name
EXIT STATUS: 0
STDOUT: "Dean Putney\n"
STDERR: ""
Skipping CaseConflicts

✗ One or more pre-commit hooks failed

git reset --hard
EXIT STATUS: 0
STDOUT: "HEAD is now at e086f18 Adding TODO comment\n"
STDERR: ""
git stash pop --index --quiet
EXIT STATUS: 0
STDOUT: ""
STDERR: ""
```

**Comment by sds** [comment] 2016-06-06 20:55
Hmm, this section of the output is interesting:

```
rubocop --format=emacs --force-exclusion --display-cop-names --config config/.rubocop.yml ... (1 splittable args)
EXIT STATUS: 1
STDOUT: "/Users/deanputney/project1/app/models/file.rb:26:3: W: Lint/UselessAccessModifier: Useless `private` access modifier.\n"
STDERR: "fatal: .git/index: index file open failed: Not a directory\nfatal: .git/index: index file open failed: Not a directory\nfatal: Not a git repository: '.git'\n"
```

Why is `rubocop` attempting to run `git` commands? Which version of RuboCop are you running, and what does your `.rubocop.yml` look like?

**Comment by deanputney** [comment] 2016-06-06 20:59
The `.rubocop.yml` is very simple:

```
# Overrides the default Rubocop settings here: https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  TargetRubyVersion: 2.1

Metrics/LineLength:
  Max: 100
```

Targeting Ruby 2.1 there is a little odd since we're on 2.3, but that doesn't seem to have anything to do with our git issue here. Is there a way to run RuboCop in the same way overcommit runs it for better debug output?

**Comment by sds** [comment] 2016-06-06 21:02
Notice that the output shows the command that is run:

```
rubocop --format=emacs --force-exclusion --display-cop-names --config config/.rubocop.yml
```

Do you have multiple `.rubocop.yml` files? Looks like it's trying to use `config/.rubocop.yml` and not the `.rubocop.yml` in the root of the repository.

**Comment by deanputney** [comment] 2016-06-06 21:06
There's only one `.rubocop.yml`, and it's in that submodule. There's no `.rubocop.yml` in the root of the repository. Running that command succeeds, even though it doesn't exclude the directories listed in `.overcommit.yml`. No unusual git error when running it standalone.

**Comment by sds** [comment] 2016-06-06 21:31
Hmm, the bizarre output maybe simply be the result of us combining the results of multiple invocations of the command (see the `CommandSplitter` class).

If you're comfortable applying a monkey patch, I'm curious what happens if you modify your Overcommit's `CommandSplitter` to have the following:

```diff
diff --git a/lib/overcommit/command_splitter.rb b/lib/overcommit/command_splitter.rb
index 3b40ff3..ca07685 100644
--- a/lib/overcommit/command_splitter.rb
+++ b/lib/overcommit/command_splitter.rb
@@ -66,6 +66,12 @@ module Overcommit
           Overcommit::Subprocess.spawn(arg_list, options)
         end

+        results.each_with_index do |result, index|
+          debug("##{index} EXIT STATUS: #{result.status}")
+          debug("##{index} STDOUT: #{result.stdout.inspect}")
+          debug("##{index} STDERR: #{result.stderr.inspect}")
+        end
+
         Result.new(results.map(&:status), results.map(&:stdout), results.map(&:stderr))
       end
```

This may help us track down what's going on here.

Alternatively, if you can reproduce this with a repository that is public, I can clone it and poke around locally.

**Comment by deanputney** [comment] 2016-06-06 21:51
That patch doesn't quite work– `debug` isn't a function and I'm not sure how the logger is instantiated there. I'll see if I can figure that out, then see if I can make a basic example repo with the same problem. I'm wondering if this is associated with my configuration somehow, as the collaborators on this project do not appear to be having this problem.

**Comment by sds** [comment] 2016-06-06 22:01
Ah, yes I didn't actually test this, sorry. Just use `puts` instead of `debug` and you'll have the same result.

**Comment by deanputney** [comment] 2016-06-06 22:04
That doesn't seem to have done too much. There's only one splittable command I guess:

```
rubocop --format=emacs --force-exclusion --display-cop-names --config config/.rubocop.yml ... (1 splittable args)
#0 EXIT STATUS: 1
#0 STDOUT: "/Users/deanputney/project1/app/models/file.rb:26:3: W: Lint/UselessAccessModifier: Useless `private` access modifier.\n"
#0 STDERR: "fatal: .git/index: index file open failed: Not a directory\nfatal: .git/index: index file open failed: Not a directory\nfatal: Not a git repository: '.git'\n"
EXIT STATUS: 1
STDOUT: "/Users/deanputney/project1/app/models/file.rb:26:3: W: Lint/UselessAccessModifier: Useless `private` access modifier.\n"
STDERR: "fatal: .git/index: index file open failed: Not a directory\nfatal: .git/index: index file open failed: Not a directory\nfatal: Not a git repository: '.git'\n"
Analyze with RuboCop........................................[RuboCop] FAILED
Errors:
fatal: .git/index: index file open failed: Not a directory
fatal: .git/index: index file open failed: Not a directory
fatal: Not a git repository: '.git'
```

**Comment by sds** [comment] 2016-06-06 22:18
Which version of RuboCop are you running? Does your `Gemfile` point to repository instead of an actual gem version?

**Comment by deanputney** [comment] 2016-06-06 22:23
RuboCop is `0.40.0`. The `Gemfile` specifies `gem 'rubocop'`.

So far I haven't been able to replicate in another repository. So that suggests that whatever I think the problem is (git directories, submodules etc.) is not what the problem actually is... I'll keep experimenting.

**Comment by deanputney** [comment] 2016-06-07 17:45
After much fiddling and uninstalling and reinstalling Ruby, I've found a potential source of the problem. Previously I was using RVM to manage my rubies, but I decided to try some other solutions since that seemed to be getting nowhere. On Ruby 2.1 as installed by ruby-install I got this error when trying to commit a change:

```
$ git ci -m "Small change"
Running pre-commit hooks
Analyze with RuboCop........................................[RuboCop] OK

✓ All pre-commit hooks passed

comparison of Gem::Version with String failed
/Users/deanputney/.gem/ruby/2.1.0/gems/overcommit-0.33.0/lib/overcommit/git_repo.rb:243:in `<'
/Users/deanputney/.gem/ruby/2.1.0/gems/overcommit-0.33.0/lib/overcommit/git_repo.rb:243:in `block in submodules'
/Users/deanputney/.gem/ruby/2.1.0/gems/iniparse-1.4.2/lib/iniparse/line_collection.rb:62:in `block in each'
/Users/deanputney/.gem/ruby/2.1.0/gems/iniparse-1.4.2/lib/iniparse/line_collection.rb:60:in `each'
/Users/deanputney/.gem/ruby/2.1.0/gems/iniparse-1.4.2/lib/iniparse/line_collection.rb:60:in `each'
/Users/deanputney/.gem/ruby/2.1.0/gems/iniparse-1.4.2/lib/iniparse/document.rb:24:in `each'
/Users/deanputney/.gem/ruby/2.1.0/gems/overcommit-0.33.0/lib/overcommit/git_repo.rb:238:in `submodules'
/Users/deanputney/.gem/ruby/2.1.0/gems/overcommit-0.33.0/lib/overcommit/git_repo.rb:225:in `staged_submodule_removals'
/Users/deanputney/.gem/ruby/2.1.0/gems/overcommit-0.33.0/lib/overcommit/hook_context/pre_commit.rb:133:in `clear_working_tree'
/Users/deanputney/.gem/ruby/2.1.0/gems/overcommit-0.33.0/lib/overcommit/hook_context/pre_commit.rb:80:in `cleanup_environment'
/Users/deanputney/.gem/ruby/2.1.0/gems/overcommit-0.33.0/lib/overcommit/hook_runner.rb:45:in `block in run'
/Users/deanputney/.gem/ruby/2.1.0/gems/overcommit-0.33.0/lib/overcommit/interrupt_handler.rb:84:in `isolate_from_interrupts'
/Users/deanputney/.gem/ruby/2.1.0/gems/overcommit-0.33.0/lib/overcommit/hook_runner.rb:28:in `run'
.git/hooks/pre-commit:79:in `<main>'
Report this bug at https://github.com/brigade/overcommit/issues
```

That points [to this comparison](https://github.com/brigade/overcommit/blob/master/lib/overcommit/git_repo.rb#L243) which I've been able to patch like this:

```patch
- if ref.nil? && GIT_VERSION < '1.8.5'
+ if ref.nil? && GIT_VERSION < Overcommit::Utils::Version.new('1.8.5')
```

That change does _not_ fix the `.git/index` issue with RVM's ruby-2.1.0, but it _does_ let me use the ruby-install version. And it might point to an area [where `git` is being called by `overcommit` directly](https://github.com/brigade/overcommit/blob/master/lib/overcommit/git_repo.rb#L245).

**Comment by sds** [comment] 2016-06-09 00:03
`GIT_VERSION` is itself a `Overcommit::Utils::Version` object, which automatically converts the right hand side operand to an `Overcommit::Utils::Version` object: https://github.com/brigade/overcommit/blob/v0.33.0/lib/overcommit/utils.rb#L16-L25

In other words, what you're seeing doesn't make any sense (it shouldn't be possible). 

Again, when we were looking at the output, the STDERR stream reporting an issue with the `.git` directory not existing was coming from `rubocop`, not Overcommit (your output in https://github.com/brigade/overcommit/issues/383#issuecomment-224102877 confirmed this).

I'm not sure what else to offer here. Without a reproducible example I'm tempted to dismiss this as PEBKAC (no offense). Would be happy to investigate if you can provide a public repo where this can be reliably reproduced!

**Comment by sds** [comment] 2016-06-23 19:04
Closing due to lack of movement. Again, if a reproducible example can be provided I'll happily investigate!

**Closed by sds** 2016-06-23 19:04 UTC
Labels: question
