### ISSUE TITLE
Bugs Adding Existing Git Hooks

### ISSUE THREAD

**Issue by jorgeorpinel** [brigade/overcommit#296] opened 2015-11-13 18:36 UTC
I'm trying to use a pre-commit custom hook as explained in [Adding Existing Git Hooks](https://github.com/brigade/overcommit#adding-existing-git-hooks) to integrate PHP_CodeSniffer -- yes, my project is PHP... My `.overcommit.yml` file looks like:
```yml
verify_plugin_signatures: false # BTW this seems mandatory when using a custom hook?

PreCommit:
  PHP_CodeSniffer:
    enabled: true
    required_executable: './vendor/bin/phpcs' # created by `composer install`
```

At first, to try it, I was running `overcommit -r" ("Run pre-commit hook against all tracked files in repository") but it ALWAYS hangs on:
```sh
$ overcommit -r
Running pre-commit hooks
...
Running PHP_CodeSniffer.............................[PHP_CodeSniffer] # Hangs here forever.
```
I tried with the "CustomScript" hook name, no dice. I also tried `OVERCOMMIT_DEBUG=true` and even `ruby -dS` before `overcommit -r` but it just always hangs there and gives no output of any kind.

Fortunatelly the hook does work with I `git commit`, but would be nice to be able to `--run` it manually.

### Other problems

* ~~It seems Overcommit is re-writing my files into Windows format line-endings (CRLF)? Why? This happens to .overcommit.yml at least.~~
_Update: never mind, this was due to my global Git settings... To [fix on Mac](https://help.github.com/articles/dealing-with-line-endings/#platform-mac):_ `git config --global core.autocrlf input `

* At some point I tried `ONLY=PHP_CodeSniffer overcommit -r` but it also skips PHP_CodeSniffer (which doesn't happen when calling the hook "CustonScript")... Is the `_` throwing Overcommit off?
```sh
$ ONLY=PHP_CodeSniffer overcommit -r
Running pre-commit hooks
Cannot skip AuthorEmail since it is required
Cannot skip AuthorName since it is required
Skipping BrokenSymlinks
Skipping CaseConflicts
Skipping MergeConflicts
Skipping PHP_CodeSniffer

✓ All pre-commit hooks passed
```
_Update: SKIP doesn't work with underscore either. I renamed my hook "PHPCodeSniffer"_

* At some point I was testing a simple shell script `run-phpcs` instead of `vendor/bin/phpcs`. YAML:
```yml
 ...
    required_executable: './run-phpcs' # has exec permissions
```
But it can't find that path... ??? Output:
```sh
$ git commit -m "Overcommit pre-commit CustomScript test"
Running pre-commit hooks
Running PHP_CodeSniffer.............................[PHP_CodeSniffer] FAILED
Hook raised unexpected error
No such file or directory - ./run-phpcs
...
```
_Update: Maybe `run-phpcs` didn't have exec permissions. Tried again (after @sds' first comment below) and it's not a problem now._

### My environment

Mac OS X 10.10.5 Terminal
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
overcommit ~~0.28.0~~ 0.29.1
Path to project: /Applications/MAMP/htdocs/some-git-repo

**Comment by sds** [comment] 2015-11-18 07:32
Hey @jorgeorpinel,

The issue here (as you guessed) is that you are including `_` in your `PHP_CodeSniffer` hook name.

Overcommit needs to use a camel case naming scheme for hooks so that it can easily translate between the hook name and its file (this is also a Ruby convention). For example, `PHP_CodeSniffer` in snake_case would be `p_h_p_code_sniffer`, but translating that snake_case form back to CamelCase would result in `PHPCodeSniffer`, so that underscore is lost in the translation.

I've added some code to print an error if your hooks contain invalid names: 4e17d61a5b79ab04913df6f0c9c3d672a9fd6b2c. Hopefully it will help prevent further confusion.

Regarding your `run-phpcs` script: is it definitely in the root of the repository? I'm not able to reproduce the issue locally.

**Comment by jorgeorpinel** [comment] 2015-11-18 19:10
Nice, thanks. I'll update and confirm the `run_script` issue is happening or not.

BUT the main problem here is that `overcommir -r` isn't able to work my non-ruby script. It hangs forever at
```sh
Running PHP_CodeSniffer.............................[PHP_CodeSniffer]
```

Any thoughts?

**Comment by sds** [comment] 2015-11-19 07:27
Hey @jorgeorpinel, sorry I forgot to address your question about hanging.

There's nothing that jumps to mind as a potential cause. You should be able to `strace` your process to see what it's blocked on, which might reveal some clues, i.e. something like:

```
$ sudo strace -p <pid>
Process <pid> attached
futex(0x18aba38, FUTEX_WAIT, 0, NULL
```

Let us know what you find.

**Comment by jorgeorpinel** [comment] 2015-11-19 15:35
Thanks. I'm on Mac OS so I used `dtruss` instead of `strace`:

```sh
$ sudo dtruss -p 22103
SYSCALL(args) 		 = return

```
It also just hangs there d:

But then I tried
```sh
$ sudo dtruss overcommit -r
...
# Super long output
...
Running PHPCodeSniffer...............................[PHPCodeSniffer] wait4(0x56FF, 0x7FFF5DA3F03C, 0x0)		 = 22271 0
lseek(0x19, 0x0, 0x0)		 = 0 0
lseek(0x18, 0x0, 0x0)		 = 0 0
fstat64(0x18, 0x7FFF5DA3E7C0, 0x0)		 = 0 0
lseek(0x18, 0x0, 0x1)		 = 0 0
sigprocmask(0x1, 0x0, 0x7FFF5DA3E500)		 = 0x0 0
sigaltstack(0x0, 0x7FFF5DA3E4F0, 0x7FFF5DA3E500)		 = 0 0
read(0x18, "\0", 0x400)		 = 0 0
fstat64(0x19, 0x7FFF5DA3E7C0, 0x400)		 = 0 0
lseek(0x19, 0x0, 0x1)		 = 0 0
sigprocmask(0x1, 0x0, 0x7FFF5DA3E500)		 = 0x0 0
sigaltstack(0x0, 0x7FFF5DA3E4F0, 0x7FFF5DA3E500)		 = 0 0
read(0x19, "grep: /path/to/project/_html/lib/libs.js: No such file or directory\ngrep: /Applications/MAMP/htdocs/PROJECT_NAME/_html/scripts: No such file or directory\ngrep: /Applications/MAMP/htdocs/PROJECT_NAME/_html/styles/css/", 0x124)		 = 292 0
sigprocmask(0x1, 0x0, 0x7FFF5DA3E500)		 = 0x0 0
sigaltstack(0x0, 0x7FFF5DA3E4F0, 0x7FFF5DA3E500)		 = 0 0
read(0x19, "lstat64\0", 0x400)		 = 0 0
sigprocmask(0x1, 0x0, 0x7FFF5DA3F150)		 = 0x0 0
sigaltstack(0x0, 0x7FFF5DA3F140, 0x7FFF5DA3F150)		 = 0 0
write(0x1, "Running PHPCodeSniffer\0", 0x16)		 = 22 0
sigprocmask(0x1, 0x0, 0x7FFF5DA3F150)		 = 0x0 0
sigaltstack(0x0, 0x7FFF5DA3F140, 0x7FFF5DA3F150)		 = 0 0
write(0x1, "...............................\0", 0x1F)		 = 31 0
sigprocmask(0x1, 0x0, 0x7FFF5DA3F150)		 = 0x0 0
sigaltstack(0x0, 0x7FFF5DA3F140, 0x7FFF5DA3F150)		 = 0 0
write(0x1, "[PHPCodeSniffer] \0", 0x11)		 = 17 0
stat64("/Applications/MAMP/htdocs/PROJECT_NAME/./vendor/bin/phpcs\0", 0x7FFF5DA3EAC8, 0x11)		 = 0 0
geteuid(0x7FF91C925C80, 0x7FFF5DA3EAC8, 0x11)		 = 0 0
fstat64(0x0, 0x7FFF5DA3F560, 0x11)		 = 0 0
sigprocmask(0x1, 0x0, 0x7FFF5DA3F2A0)		 = 0x0 0
sigaltstack(0x0, 0x7FFF5DA3F290, 0x7FFF5DA3F2A0)		 = 0 0

```
and hangs there.

Here are the links to [stat64](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man2/stat64.2.html) "obtains information about the file", [geteuid](https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man2/geteuid.2.html) "returns the effective user ID of the call", [fstat64](https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man2/fstat64.2.html) "obtains the same information about an open file known by the file descriptor", [sigprocmask](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man2/sigprocmask.2.html) "manipulate current signal mask" -- related to signal blocking --, and [sigaltstack](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man2/sigaltstack.2.html) "set and/or get signal stack context". Those are the Mac OS X calls at `./vendor/bin/phpcs`.

I don't expect you to be able to troubleshoot on Mac OS but can you maybe reproduce this on Linux?

**Comment by sds** [comment] 2015-11-20 07:39
Hey @jorgeorpinel, thanks for providing that additional information. 

I'm skeptical this is an Overcommit issue given the output, but it's hard to tell without being able to see the exact line of Ruby code your program freezes on. Typically the way I would debug issues like this would be to attach to the process with `gdb` and force Ruby to print a stacktrace, e.g.:

`gdb /path/to/ruby/executable/on/your/system <pid-of-overcommit-process>`

Once attached you can then execute:

```
call rb_backtrace()
```

...to cause the application to print a backtrace.

Other than that, I'm afraid you'll need to do some digging on your own. It's possible you're running into a bug with `ChildProcess`, the gem that Overcommit uses to spawn child processes, but it's difficult to tell from this output. If you can provide a stacktrace of where in the code things are hanging, that may help us narrow it down. 

Even better would be if you could reproduce this with a non-PHP process to rule out a PHP quirk as the cause.

**Comment by jorgeorpinel** [comment] 2015-11-20 16:01
I hear ya. Let me try to make sure it's not my environment and will give your instructions a shot!

**Comment by jorgeorpinel** [comment] 2015-11-20 19:12
DEBUG OUTPUT:

First, while `overcommit -r` is stuck at `[PHPCodeSniffer]`, I tried from a separate terminal
```sh
$ ps -a
  PID TTY          TIME CMD
...
19059 pts/1    00:00:00 overcommit
19924 pts/2    00:00:00 ps

$ sudo strace -p 19059
Process 19059 attached
read(0,
```
That's the output (hangs too).

Then, I tried `gqb` but couldn't figure out how to attach like you wanted:
```sh
$ gdb --pid 19059 `which ruby`
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
... blah
...
Reading symbols from /usr/bin/ruby...(no debugging symbols found)...done.
Attaching to program: /usr/bin/ruby, process 19059
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
(gdb) call rb_backtrace()
No symbol table is loaded.  Use the "file" command.
(gdb) quit
```

Again, the script I'm calling from Overcommit is just a bash script now, not PHP.

**Comment by jorgeorpinel** [comment] 2015-11-20 23:49
UPDATE: I accidentally forgot to kill `overcommit -r` with `^c` on the server and now that I opened that terminal tab I noticed the following output:
```sh
...
Running PHPCodeSniffer...............................[PHPCodeSniffer] 	from /usr/local/bin/overcommit:23:in `<main>'
	from /usr/local/bin/overcommit:23:in `load'
	from /var/lib/gems/1.9.1/gems/overcommit-0.29.1/bin/overcommit:7:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/overcommit-0.29.1/lib/overcommit/cli.rb:28:in `run'
	from /var/lib/gems/1.9.1/gems/overcommit-0.29.1/lib/overcommit/cli.rb:202:in `run_all'
	from /var/lib/gems/1.9.1/gems/overcommit-0.29.1/lib/overcommit/hook_runner.rb:24:in `run'
	from /var/lib/gems/1.9.1/gems/overcommit-0.29.1/lib/overcommit/interrupt_handler.rb:84:in `isolate_from_interrupts'
	from /var/lib/gems/1.9.1/gems/overcommit-0.29.1/lib/overcommit/hook_runner.rb:39:in `block in run'
	from /var/lib/gems/1.9.1/gems/overcommit-0.29.1/lib/overcommit/hook_runner.rb:58:in `run_hooks'
	from /var/lib/gems/1.9.1/gems/overcommit-0.29.1/lib/overcommit/hook_runner.rb:58:in `each'
	from /var/lib/gems/1.9.1/gems/overcommit-0.29.1/lib/overcommit/hook_runner.rb:59:in `block in run_hooks'
	from /var/lib/gems/1.9.1/gems/overcommit-0.29.1/lib/overcommit/hook_runner.rb:106:in `run_hook'
	from /var/lib/gems/1.9.1/gems/overcommit-0.29.1/lib/overcommit/interrupt_handler.rb:63:in `disable_until_finished_or_interrupted'
	from /var/lib/gems/1.9.1/gems/overcommit-0.29.1/lib/overcommit/hook_runner.rb:107:in `block in run_hook'
	from /var/lib/gems/1.9.1/gems/overcommit-0.29.1/lib/overcommit/hook/base.rb:45:in `run_and_transform'
	from /var/lib/gems/1.9.1/gems/overcommit-0.29.1/lib/overcommit/utils.rb:223:in `with_environment'
	from /var/lib/gems/1.9.1/gems/overcommit-0.29.1/lib/overcommit/hook/base.rb:45:in `block in run_and_transform'
	from /var/lib/gems/1.9.1/gems/overcommit-0.29.1/lib/overcommit/hook_loader/plugin_hook_loader.rb:83:in `run'
	from /var/lib/gems/1.9.1/gems/overcommit-0.29.1/lib/overcommit/hook_context/base.rb:31:in `execute_hook'
	from /var/lib/gems/1.9.1/gems/overcommit-0.29.1/lib/overcommit/hook_context/base.rb:87:in `input_string'
	from /var/lib/gems/1.9.1/gems/overcommit-0.29.1/lib/overcommit/hook_context/base.rb:87:in `read'
```
That's as far as it goes. My sssh session then disconnected `Write failed: Broken pipe`. Does that help determine whether it's a Overcommit or Ruby issue and where to look next?

**Comment by sds** [comment] 2015-11-21 23:16
Thanks for the detailed debugging info, @jorgeorpinel. This helped diagnose the issue.

Fix is in 9778b2964218a2aa0efd69b1704e95d3bbbd249f.

**Closed by sds** 2015-11-21 23:16 UTC
Labels: bug

**Comment by jorgeorpinel** [comment] 2015-11-21 23:39
Awesome! Thank you.

**Comment by jspiro** [comment] 2015-12-23 03:39
Any chance we can get 0.29.2 published? I'm about to merge overcommit for my company but we do have some custom hooks.

**Comment by sds** [comment] 2015-12-24 06:03
[0.30.0](https://github.com/brigade/overcommit/releases/tag/v0.30.0) has just been released.
