### ISSUE TITLE
"No such file or directory @ rb_sysopen" while amending to rename a file

### ISSUE THREAD

**Issue by eleather** [brigade/overcommit#219] opened 2015-05-29 18:57 UTC
**Problem:** Leo was amending a commit. His original commit added a file. His amend renamed that file. Overcommit was trying to run on the original file, which no longer existed (because it had been renamed).

**Solution:**
```
git stash   # stash current changes
git reset HEAD^   # reset commit he was trying to amend
rm <file that was renamed>
git add -p
git commit   # Use original commit message from gerrit, including change-id
git stash pop
git add -p
git add <new name for renamed file>
git commit --amend
```

This seems related to https://github.com/brigade/overcommit/issues/146.

**Comment by Empact** [comment] 2015-05-29 19:19
Yep, I've seen the same when amending a commit with a deleted file.

**Comment by sds** [comment] 2015-06-03 03:14
Interesting, I thought I fixed this in 4b784a9dd6b518bcadcc0708612defec5abac293, which landed in version 0.24.0. When I try to reproduce this locally I don't get any errors.

Are you seeing this in a specific hook, @emily / @leoxlin? Can you reliably reproduce and post the stack trace?

**Comment by lencioni** [comment] 2015-06-03 05:17
This reproduces it for me with overcommit 0.25.0:

```sh
mkdir tmp
cd tmp
git init
overcommit .
echo 'PreCommit:
  ScssLint:
    enabled: true' >! .overcommit.yml
git add .overcommit.yml
git commit -m 'Initial'
echo 'p { display: none; }' > test.scss
git add test.scss
git commit -m 'test.scss'
git mv test.scss test2.scss
git commit --amend
```
:bomb: :boom: 

This is what the output looks like:
```
Running pre-commit hooks
Analyzing with scss-lint...................................[ScssLint] FAILED
No such file or directory @ rb_sysopen - /path/to/tmp/test.scss


✗ One or more pre-commit hooks failed
```

**Comment by sds** [comment] 2015-06-03 19:43
Ok, this issue makes more sense then. The problem is that we aren't differentiating "modified" files from "removed" files. This only becomes an issue because amending allows you to be in a state where you are ultimately merging the individual diffs of two separate indexes.

A fix shouldn't be too hard.

**Closed** 2015-06-03 21:12 UTC
Labels: bug
