### ISSUE TITLE
Stylelint no-empty-source

### ISSUE THREAD

**Issue by mcdave029** [brigade/overcommit#593] opened 2018-08-07 10:38 UTC
Rails version: Rails 5.2.0
Ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
Node version: v10.5.0
[Clone for references](https://github.com/mcdave029/stylelint-app)

![screen shot 2018-08-07 at 6 34 46 pm](https://user-images.githubusercontent.com/4713628/43771178-ee3d339c-9a70-11e8-9798-c0fded42be50.jpg)

Thanks for the help 😊

**Comment by sds** [comment] 2018-08-09 18:41
Thanks for the report, @mcdave029.

Any thoughts on this, @Ruffeng?

**Comment by Ruffeng** [comment] 2018-08-10 06:14
@mcdave029 seems it's a rule from stylelint https://stylelint.io/user-guide/rules/no-empty-source/ . However, it doesn't seem to respect the single line compact format, the error is correct but should show the name of the file. Because it's multiline, it doesn't match the regex to know what's going on there.

I'll have a look about the output

**Comment by Ruffeng** [comment] 2018-08-10 07:59
I could reproduce the error. Didn't notice you are showing as well the output of the stylelint at the bottom of the picture. 
I'll investigate as soon as i am available :)

**Comment by Ruffeng** [comment] 2018-08-13 08:55
@mcdave029 This is the app you provided me to reproduce the error: 

<img width="1419" alt="screen shot 2018-08-13 at 10 50 57" src="https://user-images.githubusercontent.com/18511772/44022107-f8cef294-9ee6-11e8-814a-bef09ecc077e.png">

In the default.yml, I assumed you are using npm server, and I specified there the necessary flags to make it work with it. Since you append directly the `node_modules` folder, you invoked the executable but no the flag format.

To make it work:
```
PreCommit:
  Stylelint:
    enabled: true
    required_executable: 'node_modules/stylelint/bin/stylelint.js'
    command: ['node_modules/stylelint/bin/stylelint.js', '**/*.css', '-f', 'compact']
```

I hope that helps.

@sds If from his side it's correct, we can close this topic. If you want I can do a small PR with extra instructions inside the file explaining situations like this

**Comment by mcdave029** [comment] 2018-08-14 02:15
@Ruffeng thanks for the solution! 👍 it helps but i think the downside of this is. It will lint all the .css files whether its edited or not which i think its not necessary. should i use global stylelint instead of node_modules? but i produce same errors with stylelint global too. thanks! 😊

**Closed** 2019-01-20 03:42 UTC
