### ISSUE TITLE
Delay after pre commit hooks pass

### ISSUE THREAD

**Issue by ncri** [brigade/overcommit#628] opened 2019-03-29 10:10 UTC
I noticed that after the pre-commit hooks ran successfully, there is a long delay (about 25s) until my editor opens to edit the commit message. I ruled out my editor as the cause as it loads instantly when committing without overcommit. Trying to figure out what is actually happening during that delay and how to get rid of it.

**Comment by ncri** [comment] 2019-03-29 10:39
Okay, i found the issue, it's the loading of the config to check for the gemfile option in the hooks:

When I remove this call in `.git/hooks/prepare-commit-msg`

```ruby
if gemfile = YAML.load_file('.overcommit.yml')['gemfile'] rescue nil
```

My commit runs 20 secs faster! I will check if removing it in the other hooks will give more speedup.

**Comment by ncri** [comment] 2019-03-29 10:57
Odd, the behaviour is not fully consistent. Maybe there is some caching involved.

**Comment by sds** [comment] 2019-03-30 22:47
Hey @ncri, 

Loading and parsing a YAML file should not take 20 seconds. Something about your system is suspicious. This could be caused by antivirus software, syscall monitoring systems like CiscoAMP/etc., or something else, but if you're tying it to this one call, it's highly unlikely to be an Overcommit issue.

If you have some further evidence to share, would be interested. Otherwise I'm going to close this issue as it sounds like an underlying system issue.

**Closed by sds** 2019-03-30 22:47 UTC

**Comment by ncri** [comment] 2019-03-31 07:45
Sure, thanks, yes, it is odd. And also not so easy to reproduce. I will further investigate... However, my work mates also report overcommit being very slow. So that does actually point to a performance issue.
