### ISSUE TITLE
Extract built-in hooks a la pre-commit

### ISSUE THREAD

**Issue by nikolay** [brigade/overcommit#122] opened 2015-03-05 03:14 UTC
Separating the core from the hooks (even the standard ones) will improve the perception that this isn't a bloated project. I understand that most are just a few lines of code, but it doesn't hurt to put these a separate repo and load this repo by default unless overridden. Also, people can git-submodule that repo into a standard location within the project as well.

[pre-commit](http://pre-commit.com) by [Yelp](https://www.yelp.com)

**Comment by lencioni** [comment] 2015-03-05 14:09
@nikolay thanks for the suggestion! It's an interesting idea, but it does come with a fair amount of overhead that I'm not convinced is outweighed by the benefits. Are there any benefits to this that you see other than perception of bloat?

**Comment by nikolay** [comment] 2015-03-05 19:35
@lencioni To start with, you need to disable a lot of the hooks that are not relevant to your project - there shouldn't be much overhead, but there's some, for sure. Instead, you can reference packages of hooks that are relevant to you and you don't even have to enable/disable as it should use defaults. Maybe packages of hooks can be RubyGems themselves and have some discovery mechanism to avoid the Git submodule approach that pre-commit took.

**Comment by sds** [comment] 2015-03-05 20:07
Appreciate your thoughts on this, @nikolay.

I don't think the problem you're speaking to demands Overcommit be split out into separate packages of hooks just yet. To me, the issue is the manual process of having to disable hooks which aren't relevant to your needs for a repo.

In the beginning there were so few hooks that this wasn't onerous. However, we've had a significant number of hooks contributed in the last little while (though many are still disabled by default).

I'm becoming more comfortable with the idea that all (or perhaps virtually all save for some really low-level ones like `BrokenSymlink`) hooks should be opt-in. This can be accomplished with a simple modification to the default configuration rather than extracting into a separate project.

While there is still a need for Overcommit to be able to load external hooks from shared packages, I don't think this situation is one of them just yet. Overcommit only loads plugins which are enabled, and loading a large YAML configuration is not going to slow down your hook runs.

I still see something like what you suggest happening longer term. This way groups of hooks that pair well together (e.g. a set of hooks for Go development, which add necessary exceptions `HardTabs` etc.) can be distributed as a separate repo.

**Comment by nikolay** [comment] 2015-03-05 20:42
@sds @lencioni I appreciate you taking the time to respond. I'm using pre-commit and just recently found Overcomit and I like it better, so, that's why I wanted to share some of my experience.

I agree that disabling project-specific hooks will improve the user experience - opt-in is better than assuming the use case. I agree that many generic ones are totally okay to be enabled by default.

The ideas I shared are not mine and not unique to pre-commit either. Think Homebrew and Taps on OS X or PPAs on Ubuntu, and so on.

Anyway, I'm really excited and will do my best to adopt Overcommit and contribute. Thanks!

**Comment by jawshooah** [comment] 2015-03-10 09:15
I'm super on-board with making most hooks opt-in, save for a few that are not dependent on a particular project's style:

* `AuthorName`, `AuthorEmail`: No commit should ever be published without contact info.
* `BrokenSymlink`: This is almost always accidental.
* `BundleCheck`: `Gemfile.lock` should always be kept up to date. Can't think of a reason why not.
* `JsonSyntax`, `YamlSyntax`: Don't imagine anyone would intentionally commit invalid JSON or YAML.
* `LocalPathsInGemfile`: Fine for local testing, but should never be committed.
* `MergeConflicts`: Should never be committed.

**Comment by unn** [comment] 2015-03-11 15:32
As someone using overcommit on a non-ruby project, I don't need `BundleCheck` or `LocalPathsInGemfile`.

I hate to expand the scope of this request but would it make sense to create a language profile with sensible defaults per profile? Either that or provide language agnostic hooks by default.

**Comment by jawshooah** [comment] 2015-03-11 15:36
True, but those hooks only run if the files they're associated with exist in the repository. If your project is not Ruby-based, then they should never run at all. You could make the same argument for hooks like `JsonSyntax` and `YamlSyntax`, since not every project uses those formats to store metadata.

I do like the idea of language profiles, though. Not as part of the configuration implementation, but simply as different starter configs for different languages. When the user runs `overcommit --install`, we could either try to detect the repository's primary language or just present the user with a list of options.

**Comment by unn** [comment] 2015-03-11 15:39
@jawshooah I neglected to remember that but was just coming back to edit my comment to that effect.

Detection might be a pita, but dropping a language option into .overcommit.yml might be a better solution.

**Comment by jawshooah** [comment] 2015-03-11 16:23
Another argument for disabling all but the most universally agreeable hooks, and the one I find most compelling, is that whenever a user updates Overcommit, they must also disable any new unwanted hooks that have been enabled by default.

For example, we have a bunch of JavaScript linting hooks, several of which are enabled by default (`EsLint`, `Jscs`, `JsHint`, and `JsLint`). `JsLint` was just added recently; the next time Overcommit pushes a new release, anyone who updates must now disable `JsLint` in all of their JavaScript repositories if they use another linting tool. This is a hassle, and shouldn't be the user's responsibility.

**Comment by nikolay** [comment] 2015-03-18 06:42
@jawshooah I think only those 100% universal should be enabled to be future-proof.

**Comment by sds** [comment] 2015-03-27 22:58
To address this issue for now, I'm going to propose the following:

Starting with `overcommit` 0.24.0 (the next release), only the following hooks will be enabled by default:

* commit-msg
  * CapitalizedSubject
  * SingleLineSubject
  * TextWidth
  * TrailingPeriod

* post-checkout
  * (none)

* post-commit
  * (none)

* post-merge
  * (none)

* post-rewrite
  * (none)

* pre-commit
  * AuthorEmail
  * AuthorName
  * BrokenSymlinks
  * CaseConflicts
  * MergeConflicts

The remaining hooks will be opt-in. That is, they will be disabled by default until you enable them in your repository's `.overcommit.yml` file.

In the future, we'll add some basic detection during `overcommit --install` to suggest some language-specific hooks to enable for your project if you are installing `overcommit` hooks for the first time. What this looks like I'm not sure, but I think having all but the most basic of hooks be opt-in is a step towards making this tool more useful to a general audience.

Furthermore, I'll be removing language-specific configuration from hooks (e.g. removing the exception for `.go` files in the `HardTabs` pre-commit hook) since these kinds of configuration changes should also be opt-in (even if it's the norm for a language). Again, we can have some sort of suggested default that is generated in the initial `.overcommit.yml` example file when installing for the first time, but that can come later.

**Comment by lencioni** [comment] 2015-03-28 00:14
I think this sounds pretty reasonable.

> I'll be removing language-specific configuration from hooks (e.g. removing the exception for .go files in the HardTabs pre-commit hook) since these kinds of configuration changes should also be opt-in (even if it's the norm for a language).

What do you think about having sets of presets that you can choose to use. I'm thinking of something similar to JSCS's presets: https://github.com/jscs-dev/node-jscs/tree/master/presets These could be language-based but wouldn't necessarily have to be language-based. That would allow people to opt in to language specific configurations that cut across hooks, if they want.

**Comment by sds** [comment] 2015-03-28 01:47
I'm all for some sort of system to support presets, I'd just rather not have this repository be responsible for maintaining those presets. I think doing so would quickly turn this project into a forum for discussing the subjective merits of various settings for various languages. I'd like to keep the conversation focused on the framework itself.

This is where being able to load hook configurations from external repositories would be useful. Organizations can define a standard set of configuration in a single repository and then reference it in all their other repositories, tweaking on a per-repository basis as desired.

**Comment by sds** [comment] 2015-04-07 08:08
Implemented https://github.com/brigade/overcommit/issues/122#issuecomment-87114806 in 1d5dd4a and 3f7c037.

**Closed by sds** 2015-04-07 08:08 UTC
Labels: enhancement
