### ISSUE TITLE
Overcommit fails due to Rubocop config change, despite being set to 'warn'

### ISSUE THREAD

**Issue by brandondrew** [brigade/overcommit#511] opened 2017-09-12 20:31 UTC
My overcommit config says to *warn* on Rubocop failures:

```
PreCommit:
  ALL:
    quiet: false
  RuboCop:
    enabled: true
    on_fail: warn
```

But Overcommit is making my commit fail because of a change in Rubocop's config key names:

```
Analyze with RuboCop........................................[RuboCop] FAILED
Unexpected output: unable to determine line number or type of error/warning for output:
(...)/.rubocop.yml - AllCops/Excludes was renamed to AllCops/Exclude
```

**Comment by sds** [comment] 2017-09-13 04:53
Hey @brandondrew,

I would say this is expected behavior. The RuboCop pre-commit hook is not expecting the output RuboCop is outputting&mdash;it's expecting each line to be a well-formatted cop message&mdash;but instead it's getting expected output. In this case, we're actually raising an exception: https://github.com/brigade/overcommit/blob/v0.41.0/lib/overcommit/hook/pre_commit/base.rb#L31-L34

This behavior makes sense because this is not a typical "failed" hook, it's an exception that should be addressed as it's warning you that the hook is not producing expected output (in this case, you have unexpected messages in the output that should be fixed). You can see this logic defined clearly in the base hook runner implementation: https://github.com/brigade/overcommit/blob/v0.41.0/lib/overcommit/hook_runner.rb#L156-L158

Hope this helps explain the behavior. Thanks for the report!

**Closed by sds** 2017-09-13 04:53 UTC
Labels: question

**Comment by weppos** [comment] 2018-03-07 14:45
FYI the latest version of Rubocop emits a warning when overriding previous configs: https://github.com/bbatsov/rubocop/issues/4477

This is a totally legit scenario: take the case of a global company config, and a per-repo config that overrides a previous setting (as Rubocop has no capability of merging configs, as reported in the ticket above).

As a result, this legit scenario is causing the pre-commit hook to fail.

**Comment by weppos** [comment] 2018-03-07 14:46
Actually, you can ignore my previous message. I just realized that they introduced that feature in https://github.com/bbatsov/rubocop/pull/5488

**Comment by jfelchner** [comment] 2018-03-09 00:51
@sds I'm documenting improvements to that here: https://github.com/bbatsov/rubocop/issues/5640
